### ISSUE TITLE
Sample of "AlgorithmsRadixSort" failed on OpenCL device

### ISSUE THREAD

**Issue by GeoBIM2020** [m4rs-mt/ILGPU#1116]
The OpenCL device is 11th Gen Intel(R) Core i9-11980HK.

Following is error message:

Performing operations on 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz [Type: OpenCL, WarpSize: 0, MaxNumThreadsPerGroup: 8192, MemorySize: 34046320640]
Unhandled exception. ILGPU.Runtime.OpenCL.CLException: Exception of type 'ILGPU.Runtime.OpenCL.CLException' was thrown.
   at ILGPULauncher(Kernel, AcceleratorStream, KernelConfig, ArrayView1D`2, ArrayView`1, SpecializedValue`1, Int32, Int32, Int32)
   at ILGPULauncher(SpecializationCache`3, AcceleratorStream, KernelConfig, ArrayView1D`2, ArrayView`1, SpecializedValue`1, Int32, Int32, Int32)
   at ILGPU.Algorithms.RadixSortExtensions.<>c__DisplayClass23_2`3.<CreateRadixSort>b__1(AcceleratorStream stream, ArrayView1D`2 input, ArrayView`1 tempView) in C:\Users\17058\source\ILGPU\Nov\Src\ILGPU.Algorithms\RadixSortExtensions.cs:line 1261
   at AlgorithmsRadixSort.Program.Main() in C:\Users\17058\source\ILGPU\Nov\Samples\AlgorithmsRadixSort\Program.cs:line 77

**Comment by m4rs-mt** [comment]
Hi @GeoBIM2020, welcome to the ILGPU community. Thank you very much for raising this issue. Unfortunately, I'm not able to reproduce your issue at the moment. It may be an issue with an actual driver (version) being used. @MoFtZ maybe you have additional insights into this issue at the moment?

**Comment by MoFtZ** [comment]
@m4rs-mt I currently have access to a 10th Gen Intel Laptop CPU, and a 7th Gen Intel Desktop CPU, and have not been able to reproduce the problem either.

However, it is interesting that @GeoBIM2020 's CPU has `MaxNumThreadsPerGroup: 8192`. It is higher than I would expect, and I'm wondering if there is a driver issue, or if ILGPU is doing something wrong with OpenCL?

**Comment by m4rs-mt** [comment]
@MoFtZ I fully agree regarding the `MaxNumThreadsPerGroup`.  In my opinion, this value should ideally fall within the range of `[4, 128]` (usually).

**Comment by GeoBIM2020** [comment]
@m4rs-mt @MoFtZ There is no updated driver available for my CPU. Please let me know if you need me to do something.
