### ISSUE TITLE
Algorithm of Unique doesn't work with Array over 1 million on Cuda

### ISSUE THREAD

**Issue by geobimmodeling** [m4rs-mt/ILGPU#1300]
### Describe the bug

It throws following message:  (test project is attached)
[AlgorithmsUnique.zip](https://github.com/user-attachments/files/17708284/AlgorithmsUnique.zip)

ILGPU.Runtime.Cuda.CudaException
  HResult=0x80131500
  Message=a PTX JIT compilation failed
  Source=ILGPU
  StackTrace:
   at ILGPU.Runtime.Cuda.CudaException.ThrowIfFailed(CudaError cudaStatus) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\Cuda\CudaException.cs:line 130
   at ILGPU.Runtime.Cuda.CudaKernel..ctor(CudaAccelerator accelerator, PTXCompiledKernel kernel, MethodInfo launcher) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\Cuda\CudaKernel.cs:line 63
   at ILGPU.Runtime.Cuda.CudaAccelerator.CreateKernel(PTXCompiledKernel compiledKernel, MethodInfo launcher) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\Cuda\CudaAccelerator.cs:line 388
   at ILGPU.Runtime.KernelAccelerator`2.LoadKernelInternal(CompiledKernel kernel) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\KernelAccelerator.cs:line 52
   at ILGPU.Runtime.Accelerator.LoadKernel(CompiledKernel kernel) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\KernelLoading.cs:line 78
   at ILGPU.Runtime.Accelerator.DefaultKernelLoader.LoadKernel(Accelerator accelerator, CompiledKernel compiledKernel, KernelInfo& kernelInfo) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\KernelLoading.cs:line 234
   at ILGPU.Runtime.SpecializationCache`3.SpecializeKernel(TArgs& args) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\SpecializationCache.cs:line 196
   at ILGPU.Runtime.SpecializationCache`3.GetOrCreateKernel(TArgs args) in C:\Users\17058\Documents\ILGPU\Src\ILGPU\Runtime\SpecializationCache.cs:line 216
   at ILGPU.Algorithms.UniqueExtensions.<>c__DisplayClass2_0`2.<CreateUnique>b__0(AcceleratorStream stream, ArrayView`1 input, ArrayView`1 output, ArrayView`1 temp) in C:\Users\17058\Documents\ILGPU\Src\ILGPU.Algorithms\UniqueExtensions.cs:line 186
   at AlgorithmsUnique.Program.UniqueKernel(Accelerator accelerator, Int32[] values) in C:\Users\17058\Documents\ILGPU\Samples\AlgorithmsUnique\Program.cs:line 90
   at AlgorithmsUnique.Program.Main() in C:\Users\17058\Documents\ILGPU\Samples\AlgorithmsUnique\Program.cs:line 170

### Environment

- ILGPU version: [e.g., 1.5.1]
- .NET version: [e.g., .NET 7]
- Operating system: [e.g., Windows 10]
- Hardware (if GPU-related): [e.g., NVIDIA A5000 mobile]

### Steps to reproduce

[AlgorithmsUnique.zip](https://github.com/user-attachments/files/17708294/AlgorithmsUnique.zip)

### Expected behavior

Can you please fix up this bug?

**Comment by MoFtZ** [comment]
`ptxas error   : Entry function 'Kernel_UniqueKernel' uses too much shared data (0x42000 bytes, 0xc000 max)`
