### ISSUE TITLE
Jagged arrays inside a kernel

### ISSUE THREAD

**Issue by belansoft** [m4rs-mt/ILGPU#193]
HI. I'm encountering a problem when trying to operate with jagged array in a kernel.
Below is my test kernel code.
```
byte[][] test = new byte[COLUMNS][];
for (int c = 0; c < COLUMNS; c++)
  test[c] = new byte[ROWS];
```
I can successfully allocate the jagged array "test". However, once I'm trying to allocate its "columns", I get the following exception when calling LoadAutoGroupedStreamKernel:
```
Unhandled exception. System.ArgumentOutOfRangeException: Token 0x0b581707 is not valid in the scope of module Test.dll. (Parameter 'metadataToken')
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at ILGPU.Frontend.Disassembler.ResolveType(Int32 token)
   at ILGPU.Frontend.Disassembler.TryDisasembleInstruction(ILOpCode opCode)
   at ILGPU.Frontend.Disassembler.Disassemble()
   at ILGPU.Frontend.CodeGenerationPhase.GenerateCodeInternal(MethodBase method, Boolean isExternalRequest, HashSet`1 detectedMethods, Method& generatedMethod)
   at ILGPU.Frontend.ILFrontend.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
This occurs when trying to load a kernel either with CPU or Cuda accelerator.
My specs: ILGPU version is: v0.8.1-beta1, netcoreapp3.0, Linux Mint 20.

**Comment by m4rs-mt** [comment]
@belansoft Please note that jagged arrays are currently not supported. This is because arrays are reference types and you are semantically creating an array of pointers in which each element points to a different array. This requires additional class features.

**Comment by m4rs-mt** [comment]
By adding the `LocalMemory` class (as described in #316), it should be fairly easy to express your problem using explicitly allocated local-array buffers. Even multi-dimensional arrays in local memory can be easily implemented using:

```c#
var twoDView = LocalMemory.Allocate<int>(1024 * 1024).As2DView(height: 1024);
```

Since adding support for jagged arrays would require us to deal with more sophisticated class instances in the compiler, there are currently no plans to realize jagged arrays. Please use multi-dimensional local-memory allocations instead, which are able to realize the "same" behavior.

**Comment by belansoft** [comment]
Thanks Marcel! Having this ability will help my implementations looking more straightforward.
