### ISSUE TITLE
0.9.1 update to 0.9.2 throw  exception

### ISSUE THREAD

**Issue by xxl-cc** [m4rs-mt/ILGPU#329]
ILGPU.InternalCompilerException: An internal compiler error has been detected ---> System.AggregateException: 发生一个或多个错误。 ---> System.MissingMethodException: 找不到方法:“System.String ILGPU.Backends.PTX.PTXInstructions.GetArithmeticOperation(ILGPU.IR.Values.UnaryArithmeticKind, ILGPU.ArithmeticBasicValueType, Boolean)”。

stacktrace：

   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass164_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at Madic.ReconLib.Reconstruction.MadicPETReconstruction.init_madic_calc_sensitity() in E:\MadicCode\Madic.ReconLib\Reconstruction\MadicPETReconstruction.cs:line 153
   at Madic.ReconLib.Reconstruction.MadicPETReconstruction.madic_calc_sensitivity() in E:\MadicCode\Madic.ReconLib\Reconstruction\MadicPETReconstruction.cs:line 160
   at ReconTest.Recon_943Test.Test_madic_calc_sensitivity() in E:\MadicCode\ReconTest\Recon_943Test.cs:line 167

**Comment by MoFtZ** [comment]
@xxl-cc There is a breaking change in ILGPU v0.9.2 that is affecting ILGPU.Algorithms. Please wait for the next release of ILGPU.Algorithms.

**Comment by m4rs-mt** [comment]
@xxl-cc We have published a new `Algorithms` [package version](https://www.nuget.org/packages/ILGPU.Algorithms/0.9.2) that is compatible with the latest ILGPU release.
