### ISSUE TITLE
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: context is destroyed

### ISSUE THREAD

**Issue by yuryGotham** [m4rs-mt/ILGPU#367]
It looks like there is an issue with disposal of kernels when multiple threads are used. I've seen 2 different errors in such scenarios:
1)
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: invalid device context
   at ILGPU.Runtime.Cuda.CudaKernel.Dispose(Boolean disposing)
   at ILGPU.Util.DisposeBase.Finalize()
2)
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: context is destroyed
   at ILGPU.Runtime.Cuda.CudaKernel.Dispose(Boolean disposing)
   at ILGPU.Util.DisposeBase.Finalize()

The errors showed up in my fairly complex program that had 8 threads each defining a context and then compiling/executing about different 50 kernels each. I was able to reproduce with a fairly simple example - please note that this is non-deterministic, so may need to be run multiple times before it crashes with one of the above errors. I ran this specific example on 2080 Ti:

        public static void SetMemoryToConstant(Index1 index, ArrayView<float> dataView, float c)
        {
            dataView[index] = c;
        }

        public static void StressTest()
        {
            int maxThreads = 8;
            int repeat = 10000;

            Parallel.For(0, repeat, new ParallelOptions() { MaxDegreeOfParallelism = maxThreads }, r => {
                Console.WriteLine("Starting to work on " + r);
                using (var context = new Context(ILGPU.IR.Transformations.OptimizationLevel.O2))
                {
                    context.EnableAlgorithms();
                    using (var acc = new CudaAccelerator(context))
                    {
                        var k1 = acc.LoadAutoGroupedStreamKernel<Index1, ArrayView<float>, float>(SetMemoryToConstant);
                        using (var data = acc.Allocate<float>(1024 * 1024)) // 4MB
                        {
                            k1((Index1)data.Extent, data, r);
                        }
                    }
                }
                Console.WriteLine("Done with " + r);
            });
        }

**Comment by m4rs-mt** [comment]
@yuryGotham This should clearly not happen. I wasn't able to reproduce your issue on different build machines. However, I am currently investigating other potential concurrency issues related to a similar issue. I am going to take a closer look on the synchronization of the accelerator GC implementation.

**Comment by yuryGotham** [comment]
@m4rs-mt I'm very surprised that you were not able to reproduce with the code that I provided - it always crashes for me. I ran it ~10 times and it never went through more than 5% of the 10,000 iterations before crashing...

I will test to see if it still crashes when you think you may have a fix.

In the meanwhile I converted my program to serially create a bunch of context/accelerator objects when the program starts and reuse them - it is quite a pain...

**Comment by m4rs-mt** [comment]
I am going to investigate this issue in more detail in the upcoming week. However, I am also wondering about the need for multiple contexts in general. It is also possible (and advised) to reuse the same context even in the case of multiple accelerator instances. Furthermore, it is also possible to use the same accelerator instance with multiple threads. However, if you target multiple devices, you clearly have to use multiple accelerator instances. Creating many accelerator instances on the same device often leads to critical issues with respect to the GPU drivers being used.

Can you give me more information about your target platform and the current driver version?

**Comment by yuryGotham** [comment]
When I was reproducing the error, I ran the code that I provided on my home machine:
Video:
NVIDIA GeForce RTX 2080 Ti
Driver date: 7/24/2019
Driver version: 26.21.14.3200

System:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19042 Build 19042
Processor	AMD Ryzen Threadripper 3990X 64-Core Processor, 2895 Mhz, 64 Core(s), 64 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 0702, 12/12/2019
SMBIOS Version	3.2
Embedded Controller Version	255.255
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	ROG ZENITH II EXTREME
BaseBoard Version	Rev 1.xx
Hardware Abstraction Layer	Version = "10.0.19041.488"

I also just changed my code to not re-create the context and it still crashes with the same error. New code:
```
            using (var context = new Context(ILGPU.IR.Transformations.OptimizationLevel.O2)){
                Console.WriteLine("New CODE!");
                context.EnableAlgorithms();
                Parallel.For(0, repeat, new ParallelOptions() { MaxDegreeOfParallelism = maxThreads }, r => {
                    Console.WriteLine("Starting to work on " + r);
                    using (var acc = new CudaAccelerator(context)){
                        var k1 = acc.LoadAutoGroupedStreamKernel<Index1, ArrayView<float>, float>(SetMemoryToConstant);
                        using (var data = acc.Allocate<float>(1024 * 1024)) // 4MB
                        { k1((Index1)data.Extent, data, r); }
                    }
                    Console.WriteLine("Done with " + r);
                });
            }
```

Error/partial output:

```
Done with 46
Starting to work on 47
Done with 1297
Starting to work on 1298
Done with 2546
Starting to work on 2547
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: context is destroyed
   at ILGPU.Runtime.Cuda.CudaKernel.Dispose(Boolean disposing)
   at ILGPU.Util.DisposeBase.Finalize()
Done with 8795
Starting to work on 8796
Done with 6296
Starting to work on 6297
```

So it looks like the problem is not the context. Maybe accelerator disposal...
I originally bumped into this exception when trying to scale my program on Azure's 8-GPU Standard_ND40rs_v2 instance with the latest drivers. There were only 8 threads in my program and each did a lot of work on GPUs (multiple minutes of GPU runtime using 20+ kernels and 20+ buffers). Each of the 8 threads generally completed the work around the same time and once every ~10 completions my program would crash in CudaKernel.Dispose(). What I'm trying to say is that this issue happens pretty consistently without spawning thousands of threads. A few heavy Accelerator instances is probably enough.

I currently mitigated the issue by reusing accelerator objects, but it's a huge pain and risks GPU memory leaks...

**Comment by m4rs-mt** [comment]
Thank you very much for the additional insights. Are you currently running your application with the .Net Framework or the .Net Core runtime system?

On additional thing you could try is disable the explicit kernel cache to see whether the problem is related to a concurrency issue inside the internal smart caches. To do so, you can pass the `ContextFlags.DisableKernelCaching` to the `Context` constructor.

**Comment by m4rs-mt** [comment]
@yuryGotham I was finally able to reproduce this issue in `Release` mode, using 128 threads, using .Net 4.8 and your sample code provided.

**Comment by yuryGotham** [comment]
> Thank you very much for the additional insights. Are you currently running your application with the .Net Framework or the .Net Core runtime system?
> 
> On additional thing you could try is disable the explicit kernel cache to see whether the problem is related to a concurrency issue inside the internal smart caches. To do so, you can pass the `ContextFlags.DisableKernelCaching` to the `Context` constructor.

I changed the code to disable the kernel caching:
`            using (var context = new Context(ContextFlags.DisableKernelCaching, ILGPU.IR.Transformations.OptimizationLevel.O2))`
and it still crashes in the same way on my home machine.

I target .NET Core 3.1 framework.

**Comment by m4rs-mt** [comment]
I was able to narrow the problem down to the interop layer with the NVIDIA driver API. According to the documentation, "most/big/all" parts of the driver context API should be *thread-safe*. However, I am able to create out-of-memory exceptions using the following program:
```c#
public static void Main()
{
    int maxThreads = 128;
    int repeat = 100;
    int iterationsPerThread = 10;

    using (var context = new Context())
    {
        for (int i = 0; i < repeat; ++i)
        {
            var threads = new Thread[maxThreads];
            for (int j = 0; j < maxThreads; ++j)
            {
                var thread = new Thread(() =>
                {
                    for (int k = 0; k < iterationsPerThread; ++k)
                    {
                        // Create and dispose an empty accelerator context
                        using (var acc = new CudaAccelerator(context))
                        {
                            // Do nothing
                        }
                    }
                });
                threads[j] = thread;
            }

            foreach (var t in threads)
                t.Start();

            foreach (var t in threads)
                t.Join();
        }
    }
}
```
It essentially creates and disposes empty context that can lead to non-deterministic allocation/free operations that actually leak memory on the GPU. This behavior is related to the problem you are currently experiencing. Synchronizing the calls to the context management functions inside ILGPU (instead of relying on the internal driver implementations) solves this issue on our side. However, I am going to investigate the issue in more detail in order to come up with an additional synchronization layer inside ILGPU to avoid race conditions inside the drivers.

**Comment by m4rs-mt** [comment]
After further investigation, it turns out that it is also *not* possible to allocate 128 contexts on a single GPU. Although it works on an RTX 3090 with 56 contexts without allocating a single byte of memory on the device. Any number of parallel contexts over 56 immediately allocates at least 20 GB on my device. So this is clearly not a concurrency issue, but an internal driver limitation/problem.

**Comment by m4rs-mt** [comment]
I have found a critical issue inside the automatic disposal functionality 😟  -----> working on a patch 🤓

**Comment by m4rs-mt** [comment]
There were several issues related to the .Net GC and some "dangerous" properties on several `MemoryBuffer` API related objects. Using objects exposed by these properties could lead to unexpected crashes due to exposing the ownership of nested child objects to the outside world.
