### ISSUE TITLE
is not DateTime supported?

### ISSUE THREAD

**Issue by AnakinCN** [m4rs-mt/ILGPU#377]
When I use some computation functions with DateTime in my struct, it says:

```
NotSupportedException: The type 'System.DateTime' has an unsupported structure layout

ILGPU.InternalCompilerException
  HResult=0x80131500
  Message='An internal compiler error has been detected' in method Void CompareKernel(ILGPU.Index1, ILGPU.ArrayView`1[System.Boolean], BlackILGPU.Envelope, BlackILGPU.Envelope, System.TimeSpan) declared in type BlackILGPU.Program
  Source=ILGPU
  StackTrace:
   at ILGPU.Backends.Backend.PreCompileKernelMethod[TBackendHook](EntryPointDescription& entry, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass164_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TKernelLoader](EntryPointDescription entry, KernelSpecialization specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at BlackILGPU.Program.Main(String[] args) in D:\ProjectFloat\BlackILGPU\BlackILGPU\Program.cs:line 35

  This exception was originally thrown in this call stack:
    ILGPU.IR.Types.TypeInformationManager.CreateCompoundTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateCompoundTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.GetTypeInfoInternal(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateCompoundTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateCompoundTypeInfo(System.Type)
    ILGPU.IR.Types.TypeInformationManager.CreateTypeInfo(System.Type)
    ...
```

Is not DateTime supported?

**Comment by m4rs-mt** [comment]
@AnakinCN thank you for your question and welcome the the ILGPU community. Unfortunately, `System.DateTime` seems to be annotated with the `[StructLayout(LayoutKind.Auto)]` attribute. This does not allow ILGPU to determine actual byte offsets for the underlying data fields (for marshalling purposes, for instance). Instead of passing a `DateTime` structure to the kernel, you can convert it into its binary `long` representation and convert it back to a `DateTime` instance in the scope of your kernel.

**Comment by AnakinCN** [comment]
Thank you.
