### ISSUE TITLE
an plain integer variable throws exception

### ISSUE THREAD

**Issue by AnakinCN** [m4rs-mt/ILGPU#417]
Hi,

I've been converting my project into ILGPU-supported. But a plain int variable '**Cursor**' throws run-time compile exception, saying:

```
ILGPU.InternalCompilerException
  HResult=0x80131500
  Message='An internal compiler error has been detected' in file 'D:\BlackStarILGPU\BlackStarILGPU\Envelope.cs' lines 88 - 88
  Source=ILGPU
  StackTrace:
   at ILGPU.Backends.Backend.PreCompileKernelMethod[TBackendHook](EntryPointDescription& entry, TBackendHook backendHook) in /_/Src/ILGPU/Backends/Backend.cs:line 589
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook) in /_/Src/ILGPU/Backends/Backend.cs:line 624
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization) in /_/Src/ILGPU/Backends/Backend.cs:line 607
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 571
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 438
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass164_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 466
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 400
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TKernelLoader](EntryPointDescription entry, KernelSpecialization specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 461
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 329
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 559
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 546
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action) in /_/Src/ILGPU/Runtime/KernelLoaders.cs:line 1774
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at BlackStarILGPU.Program.ByGPU() in D:\BlackStarILGPU\BlackStarILGPU\Program.cs:line 88
   at BlackStarILGPU.Program.Main(String[] args) in D:\BlackStarILGPU\BlackStarILGPU\Program.cs:line 28

Internal Exception 1:
InvalidOperationException: An internal compiler error has been detected

```

[BlackStarILGPU.zip](https://github.com/m4rs-mt/ILGPU/files/5977102/BlackStarILGPU.zip)

Did I do something wrong with the variable Cursor?

Thank you.

**Comment by MoFtZ** [comment]
When I rearrange `ArrayStruct`, so that `Cursor` is declared before `Array`, the error seems to go away.

Could you try:
```CSharp
public unsafe struct ArrayStruct
{
    public int Cursor;    // Declared before Array, rather than after.
    public fixed float Array[255];
}
```
