### ISSUE TITLE
passed on CPU Accelerator but failed on GTX960

### ISSUE THREAD

**Issue by AnakinCN** [m4rs-mt/ILGPU#420]
My Kernel passed on the first AcceleratorId (CPU) but failed on 2nd AcceleratorId (GTX960), saying:

_ILGPU.Runtime.Cuda.CudaException:“a PTX JIT compilation failed”

ILGPU.Runtime.Cuda.CudaException
  HResult=0x80131500
  Message=a PTX JIT compilation failed
  Source=ILGPU
  StackTrace:
   at ILGPU.Runtime.Cuda.CudaException.ThrowIfFailed(CudaError cudaStatus) in /_/Src/ILGPU/Runtime/Cuda/CudaException.cs:line 110
   at ILGPU.Runtime.Cuda.CudaKernel..ctor(CudaAccelerator accelerator, PTXCompiledKernel kernel, MethodInfo launcher) in /_/Src/ILGPU/Runtime/Cuda/CudaKernel.cs:line 71
   at ILGPU.Runtime.Cuda.CudaAccelerator.CreateKernel(PTXCompiledKernel compiledKernel) in /_/Src/ILGPU/Runtime/Cuda/CudaAccelerator.cs:line 633
   at ILGPU.Runtime.KernelAccelerator`2.LoadAutoGroupedKernelInternal(CompiledKernel kernel, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelAccelerator.cs:line 108
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel(CompiledKernel kernel, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 193
   at ILGPU.Runtime.Accelerator.AutoKernelLoader.LoadKernel(Accelerator accelerator, CompiledKernel compiledKernel, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 291
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 439
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass173_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 466
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 400
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TKernelLoader](EntryPointDescription entry, KernelSpecialization specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelCache.cs:line 461
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 329
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 559
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method) in /_/Src/ILGPU/Runtime/KernelLoading.cs:line 546
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action) in /_/Src/ILGPU/Runtime/KernelLoaders.cs:line 1774
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4](Accelerator accelerator, Action`5 action)
   at BlackStarILGPU.Program.ByGPU() in D:\BlackStarILGPU\BlackStarILGPU\Program.cs:line 100
   at BlackStarILGPU.Program.Main(String[] args) in D:\BlackStarILGPU\BlackStarILGPU\Program.cs:line 37_

Did I miss something? Thank you in advance.
[BlackStarILGPU.zip](https://github.com/m4rs-mt/ILGPU/files/5983389/BlackStarILGPU.zip)

**Comment by MoFtZ** [comment]
The exception thrown by ILGPU is:
`ILGPU.Runtime.Cuda.CudaException: 'a PTX JIT compilation failed'`

When I run the sample program with ILGPU source code, the error returned by PTXAS is:
```
Entry function 'ILGPUKernel' uses too much parameter space (0x1c1c bytes, 0x1100 max).
```

You will need to restructure your code.

**Comment by AnakinCN** [comment]
Hi. Thank you for running my code.

> Entry function 'ILGPUKernel' uses too much parameter space (0x1c1c bytes, 0x1100 max).

I decreased the array length from 255 to 16 and it passed.
