### ISSUE TITLE
Math.Round(double) causes internal compiler error on .NET 5.0

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#425]
Code:
```
        static void Main(string[] args) {
            using var AcceleratorContext = new Context(ILGPU.IR.Transformations.OptimizationLevel.O2);
            AcceleratorContext.EnableAlgorithms();
            using var Accelerator = new CudaAccelerator(AcceleratorContext) as Accelerator;
            var kernel = Accelerator.LoadAutoGroupedStreamKernel<Index1, ArrayView<double>>(MyKernel);
        }

        public static void MyKernel(Index1 index, ArrayView<double> output) {
            output[index] = Math.Round(1.0);
        }
```

Exception:
```
Unhandled exception. ILGPU.InternalCompilerException: 'An internal compiler error has been detected' in method Double Int64BitsToDouble(Int64) declared in type System.BitConverter
 ---> System.NotSupportedException: Not supported runtime method 'get_IsSupported'
   --- End of inner exception stack trace ---
   at ILGPU.Backends.Backend.PreCompileKernelMethod[TBackendHook](EntryPointDescription& entry, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass173_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1](Accelerator accelerator, Action`2 action)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1](Accelerator accelerator, Action`2 action)
   at FurrowUtilities.Misc.Main(String[] args) in C:\main\FurrowUtilities\Misc\Misc.cs:line 69
```

My original code (before simplification for this repro) passed a variable to Math.Round, and gave the same Exception.

This is with ILGPU 0.10.0 straight off of NuGet, and net5.0 as the TargetFramework.

This is trivial to work around for my use case, so it isn't a high-priority item for me.

**Comment by m4rs-mt** [comment]
@Ruberik Thank you for your issue report. This definitely seems to be a bug.
