### ISSUE TITLE
ILGPU crashes when compiling a very simple OpenCL Kernel

### ISSUE THREAD

**Issue by yuryGotham** [m4rs-mt/ILGPU#497]
Code:
```
        public static void TestClFail() {
            using (var context = new Context(ILGPU.IR.Transformations.OptimizationLevel.Debug)) {
                Console.WriteLine("Optimization level: " + context.OptimizationLevel);
                foreach (var accId in Accelerator.Accelerators) {
                    if (accId.AcceleratorType == AcceleratorType.OpenCL) {
                        using (var acc = Accelerator.Create(context, accId)) {
                            Console.WriteLine(DateTime.Now + "\tAccelerator: " + acc.Name);
                            var sumKernel = acc.LoadStreamKernel<ArrayView<float>, ArrayView<float>>(OpenClFailKernel);
                        }
                    }
                }
            }
        }

        public static void OpenClFailKernel(
            ArrayView<float> data,
            ArrayView<float> sum
            ) {
            float localSum = 0;

            for (int itemId = 0; itemId < 1; itemId++) {
                localSum += data[itemId];
            }

            Atomic.Add(ref sum[0], localSum);
        }
```

Output:
```
Optimization level: O0
6/6/2021 4:48:22 PM     Accelerator: gfx906
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI.BuildProgram(IntPtr, IntPtr, System.String)
   at ILGPU.Runtime.OpenCL.CLKernel.LoadKernel(ILGPU.Runtime.OpenCL.CLAccelerator, System.String, ILGPU.Backends.OpenCL.CLCVersion, IntPtr ByRef, IntPtr ByRef, System.String ByRef)
   at ILGPU.Runtime.OpenCL.CLKernel..ctor(ILGPU.Runtime.OpenCL.CLAccelerator, ILGPU.Backends.OpenCL.CLCompiledKernel, System.Reflection.MethodInfo)
   at ILGPU.Runtime.OpenCL.CLAccelerator.CreateKernel(ILGPU.Backends.OpenCL.CLCompiledKernel, System.Reflection.MethodInfo)
   at ILGPU.Runtime.KernelAccelerator`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoadKernelInternal(ILGPU.Backends.CompiledKernel)
   at ILGPU.Runtime.Accelerator.LoadKernel(ILGPU.Backends.CompiledKernel)
   at ILGPU.Runtime.Accelerator+DefaultKernelLoader.LoadKernel(ILGPU.Runtime.Accelerator, ILGPU.Backends.CompiledKernel, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator+<>c__DisplayClass173_0`1[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]].<LoadGenericKernel>b__0(DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, CachedKernelLoader`2<System.__Canon,DefaultKernelLoader>, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription, ILGPU.Runtime.KernelSpecialization, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadKernel[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.MethodInfo, ILGPU.Runtime.KernelSpecialization, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.KernelLoaders.LoadKernel[[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`2<ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Single>>, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.KernelLoaders.LoadStreamKernel[[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null],[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`2<ILGPU.ArrayView`1<Single>,ILGPU.ArrayView`1<Single>>, ILGPU.Runtime.KernelInfo ByRef)
   at ConsoleTest.KnnCpu.TestClFail()
   at ConsoleTest.Program.Main(System.String[])
```

**Comment by m4rs-mt** [comment]
@yuryGotham Thanks for posting this issue. I tried the program myself and the OpenCL code generated by ILGPU >= `v0.10.1` looks okay to me at first glance. Also, I can load (and even run) the OpenCL program on several AMD and Intel cards.

The stack trace also indicates (via `at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)`) that the OpenCL driver crashes internally. Can you provide more information about this issue so we can investigate it?

**Comment by yuryGotham** [comment]
I have Windows 10 Pro with Radeon Pro VII and latest drivers installed (Radeon Pro Software Version 21.Q1.2), as well as the latest ILGPU NuGet (0.10.1).

I just found a much simpler kernel that also crashes during compile. Code:
```
        public static void OpenClFailKernel(
            ArrayView<float> sum
            ) {
            int itemId = 0;
            while (true) itemId++;
        }
```
Error - different from before:
```
Optimization level: O0
6/6/2021 7:37:00 PM     Accelerator: gfx906
Unhandled exception. ILGPU.InternalCompilerException: An internal compiler error has been detected
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ILGPU.IR.IRContext.Import_Sync(Method source)
   at ILGPU.IR.IRContext.Import(Method source)
   at ILGPU.IR.Method.ExtractToContext(Method& method)
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   --- End of inner exception stack trace ---
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass173_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadKernel[TDelegate](MethodInfo method, KernelSpecialization specialization, KernelInfo& kernelInfo)
   at ILGPU.Runtime.KernelLoaders.LoadKernel[T1](Accelerator accelerator, Action`1 action, KernelInfo& kernelInfo)
   at ILGPU.Runtime.KernelLoaders.LoadStreamKernel[T1](Accelerator accelerator, Action`1 action, KernelInfo& kernelInfo)
   at ConsoleTest.KnnCpu.TestClFail() in C:\Development\PerformanceTesting\ConsoleTest\KnnCpu.cs:line 22
   at ConsoleTest.Program.Main(String[] args) in C:\Development\PerformanceTesting\ConsoleTest\Program.cs:line 37
```
It looks to me like some of loop optimizations are misfiring...

**Comment by yuryGotham** [comment]
That latest kernel compilation also crashes for CUDA and CPU.

**Comment by MoFtZ** [comment]
@yuryGotham
That kernel is not supported by ILGPU - it is an infinite loop, which would mean the GPU kernel never finishes.

Could you try a kernel like:
```CSharp
public static void SimpleKernel(ArrayView<float> sum)
{
    sum[0] = 0.0f;
}
```

**Comment by yuryGotham** [comment]
This compiles just fine:
```
public static void SimpleKernel(ArrayView<float> sum)
{
    sum[0] = 0.0f;
}
```

But this fails:
```
        public static void OpenClFailKernel(
            ArrayView<float> sum
            ) {
            for (int i = 0; i < 1; i++) ;
            Atomic.Add(ref sum[0], 1);
        }
```
With error:
```
Optimization level: O0
6/7/2021 8:45:36 AM     Accelerator: gfx906
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram_Import(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI_0.clBuildProgram(IntPtr, Int32, IntPtr*, System.String, IntPtr, IntPtr)
   at ILGPU.Runtime.OpenCL.CLAPI.BuildProgram(IntPtr, IntPtr, System.String)
   at ILGPU.Runtime.OpenCL.CLKernel.LoadKernel(ILGPU.Runtime.OpenCL.CLAccelerator, System.String, ILGPU.Backends.OpenCL.CLCVersion, IntPtr ByRef, IntPtr ByRef, System.String ByRef)
   at ILGPU.Runtime.OpenCL.CLKernel..ctor(ILGPU.Runtime.OpenCL.CLAccelerator, ILGPU.Backends.OpenCL.CLCompiledKernel, System.Reflection.MethodInfo)
   at ILGPU.Runtime.OpenCL.CLAccelerator.CreateKernel(ILGPU.Backends.OpenCL.CLCompiledKernel, System.Reflection.MethodInfo)
   at ILGPU.Runtime.KernelAccelerator`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoadKernelInternal(ILGPU.Backends.CompiledKernel)
   at ILGPU.Runtime.Accelerator.LoadKernel(ILGPU.Backends.CompiledKernel)
   at ILGPU.Runtime.Accelerator+DefaultKernelLoader.LoadKernel(ILGPU.Runtime.Accelerator, ILGPU.Backends.CompiledKernel, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator+<>c__DisplayClass173_0`1[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]].<LoadGenericKernel>b__0(DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, CachedKernelLoader`2<System.__Canon,DefaultKernelLoader>, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription, ILGPU.Runtime.KernelSpecialization, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ILGPU.Runtime.Accelerator+DefaultKernelLoader, ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Backends.EntryPoints.EntryPointDescription ByRef, ILGPU.Runtime.KernelSpecialization ByRef, DefaultKernelLoader ByRef, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.Accelerator.LoadKernel[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.MethodInfo, ILGPU.Runtime.KernelSpecialization, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.KernelLoaders.LoadKernel[[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`1<ILGPU.ArrayView`1<Single>>, ILGPU.Runtime.KernelInfo ByRef)
   at ILGPU.Runtime.KernelLoaders.LoadStreamKernel[[ILGPU.ArrayView`1[[System.Single, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], ILGPU, Version=0.10.1.0, Culture=neutral, PublicKeyToken=null]](ILGPU.Runtime.Accelerator, System.Action`1<ILGPU.ArrayView`1<Single>>, ILGPU.Runtime.KernelInfo ByRef)
   at ConsoleTest.KnnCpu.TestClFail()
   at ConsoleTest.Program.Main(System.String[])
```
Any kernel that I tried that contains a loop (for or while) followed by an Atomic.Add fails to compile with OpenCL . CUDA and CPU work just fine.

**Comment by yuryGotham** [comment]
One other observation that I have is that something has changed with OpenCL handling. I've always had a test implemented that measures memset, memcopy and a very basic compute performance. All three tests still work for OpenCL (they don't use Atomc.Add). However, for OpenCL there is now an exception being thrown at the end of the execution:
```
Unhandled exception. ILGPU.Runtime.OpenCL.CLException: Exception of type 'ILGPU.Runtime.OpenCL.CLException' was thrown.
   at ILGPU.Runtime.OpenCL.CLMemoryBuffer`2.DisposeAcceleratorObject(Boolean disposing)
   at ILGPU.Runtime.AcceleratorObject.DisposeAcceleratorObject_Accelerator(Boolean disposing)
   at ILGPU.Runtime.Accelerator.DisposeChildObject_AcceleratorObject(AcceleratorObject acceleratorObject, Boolean disposing)
   at ILGPU.Runtime.AcceleratorObject.Dispose(Boolean disposing)
   at ILGPU.Util.DisposeBase.DisposeDriver(Boolean disposing)
   at ILGPU.Util.DisposeBase.Dispose()
   at ILGPU.Runtime.MemoryBuffer`1.DisposeAcceleratorObject(Boolean disposing)
   at ILGPU.Runtime.Accelerator.DisposeChildObjects_SyncRoot(Boolean disposing)
   at ILGPU.Runtime.Accelerator.Dispose(Boolean disposing)
   at ILGPU.Util.DisposeBase.DisposeDriver(Boolean disposing)
   at ILGPU.Util.DisposeBase.Dispose()
   at ConsoleTest.TestMM.TestGpuMemoryBandwidth() in C:\Development\PerformanceTesting\ConsoleTest\TestMM.cs:line 4984
   at ConsoleTest.Program.Main(String[] args) in C:\Development\PerformanceTesting\ConsoleTest\Program.cs:line 34

```
I don't know if it is related to the Atomic.Add() compile failures or just a totally different bug.

**Comment by MoFtZ** [comment]
> One other observation that I have is that something has changed with OpenCL handling.

It looks like  you are currently using ILGPU v0.10.1.
What was the previous version of ILGPU that you were using?

**Comment by yuryGotham** [comment]
Unfortunately I can't tell for sure as this is in the code that is not version controlled. I have not updated the ILGPU NuGet for about 8 months...

**Comment by MoFtZ** [comment]
That would probably be ILGPU [v0.9.0](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.0), [v0.9.1](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.1) or [v0.9.2](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.2).

None of the changes stands out to me, but maybe this issue related to atomics https://github.com/m4rs-mt/ILGPU/pull/321 in ILGPU v0.9.2?

Are you able to try these older versions of ILGPU, to see if the problem still exists?

**Comment by yuryGotham** [comment]
The disposal crash seems to be unrelated to Atomic.Add() crash and first appears when going from 0.9.2  to 0.10.0

**Comment by yuryGotham** [comment]
The Atomic.Add() crashes during compiling as far back as I can easily downgrade - without breaking all my code (v0.9.0). I just never used Atomic.Add() and OpenCL before.

**Comment by yuryGotham** [comment]
> That would probably be ILGPU [v0.9.0](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.0), [v0.9.1](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.1) or [v0.9.2](https://github.com/m4rs-mt/ILGPU/releases/tag/v0.9.2).
> 
> None of the changes stands out to me, but maybe this issue related to atomics #321 in ILGPU v0.9.2?
> 
> Are you able to try these older versions of ILGPU, to see if the problem still exists?

The Atomic.Add() issue is really weird because it only happens if there is a loop AND Atomic.Add().

This fails:
```
        public static void OpenClFailKernel(
            ArrayView<float> sum
            ) {
            for (int i = 0; i < 1; i++) ;
            Atomic.Add(ref sum[0], 1);
        }
```
While this work fine:
```
        public static void OpenClFailKernel(
            ArrayView<float> sum
            ) {
            //for (int i = 0; i < 1; i++) ;
            Atomic.Add(ref sum[0], 1);
        }
```
Also, I tested a few medium complexity kernels (multiple for loops and Barrier, but no Atomic.Add()) and they all work fine with OpenCL...

**Comment by MoFtZ** [comment]
Based on the information you have provided, unfortunately, this sounds like a driver issue.

We previously had a member of the community who had a (possibly) related issue on an RX 580.

In their case, if they used two consecutive for loops, the OpenCL `BuildProgram` function would throw the same exception as in your issue: `System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

e.g. This would fail for them:
```CSharp
public static void TestKernel(Index1 index)
{
    int[] test = new int[255];

    for (int i = 0; i < 255; i++)
    {
        test[i] = i + 1;
    }

    int test2 = 0;

    for (int j = 0; j < 255; j++)
    {
        test2 = j + 1;
    }
}
```

That user was able to use a workaround to avoid the exception. Instead of a regular for-loop, they wrote a `ForLoop` function that mimicked a regular for loop.
```CSharp
int n = 0;
do
{
    test[n] = n;
} while ((ForLoop(ref n, 64, 1)));

public static bool ForLoop(ref int counter, int end, int increment = 1)
{
    counter += increment;
    if (counter < end)
        return true;
    return false;
}
```

**Comment by MoFtZ** [comment]
@m4rs-mt Could there be an issue with the API binding for `clCreateProgramWithSource`?

Currently, ILGPU has a binding of:
```CSharp
        [DllImport(LibNameWindows,
            EntryPoint = "clCreateProgramWithSource"
            , BestFitMapping = false
            , CharSet = CharSet.Ansi
        )]
        [DefaultDllImportSearchPaths(DllImportSearchPath.SafeDirectories)]
        internal static extern IntPtr
            clCreateProgramWithSource_Import(
            [In] IntPtr context,
            [In] int numPrograms,
            [In] ref string source,
            [In] ref IntPtr lengths,
            [Out] out CLError errorCode);
```

And the OpenCL 2.0 documentation says it should be:
```C
cl_program clCreateProgramWithSource(
    cl_context context,
    cl_uint count,
    const char **strings,
    const size_t *lengths,
    cl_int *errcode_ret);
```

`strings` and `lengths` are supposed to be arrays, but the C# binding is using `ref`. Are the bindings correct?

**Comment by MoFtZ** [comment]
@yuryGotham I'm not sure if this will fix your issue, but I have updated the ILGPU binding for `clCreateProgramWithSource`.

The code is based on v0.10.1, on a [private branch](https://github.com/MoFtZ/ILGPU/tree/bug/cl-program-source).
The nuget package was obtained from the [CI build](https://github.com/MoFtZ/ILGPU/actions/runs/944772131) for that branch.

[nuget-package.zip](https://github.com/m4rs-mt/ILGPU/files/6666661/nuget-package.zip)

When you have time, could you please try using this nuget package to check if it resolves your issue? Thanks.

**Comment by yuryGotham** [comment]
> @yuryGotham I'm not sure if this will fix your issue, but I have updated the ILGPU binding for `clCreateProgramWithSource`.
> 
> The code is based on v0.10.1, on a [private branch](https://github.com/MoFtZ/ILGPU/tree/bug/cl-program-source).
> The nuget package was obtained from the [CI build](https://github.com/MoFtZ/ILGPU/actions/runs/944772131) for that branch.
> 
> [nuget-package.zip](https://github.com/m4rs-mt/ILGPU/files/6666661/nuget-package.zip)
> 
> When you have time, could you please try using this nuget package to check if it resolves your issue? Thanks.

I'm seeing the same exception with the pre-release nuget package that you provided...
