### ISSUE TITLE
Debug Assertion Failed: Invalid Structure Type on LoadAutoGroupedStreamKernel

### ISSUE THREAD

**Issue by Czorio** [m4rs-mt/ILGPU#53]
I am trying to implement a terrain erosion algorithm in which a decent chunk of variables and ArrayView2Ds need to be used. Unfortunately, when I try to run the code, an exception is thrown.

The main window in VS2019 shows that kernel32.pdb is not loaded, however I found out that the real stack trace is in the output window.

```
'SculptorCore.exe' (CoreCLR: clrhost): Loaded 'ILGPURuntime'. 
'SculptorCore.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\Microsoft.DiaSymReader.Native.amd64.dll'. 
'SculptorCore.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Diagnostics.StackTrace.dll'. 
'SculptorCore.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SculptorCore.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Metadata.dll'. 
'SculptorCore.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Invalid structure type
---- Assert Long Message ----

   at ILGPU.IR.Types.IRTypeContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.IRContext.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type, MemoryAddressSpace addressSpace)
   at ILGPU.IR.Construction.IRBuilder.CreateType(Type type)
   at ILGPU.Frontend.Block.PopMethodArgs(MethodBase methodBase, Value instanceValue)
   at ILGPU.Frontend.CodeGenerator.MakeCall(Block block, IRBuilder builder, MethodBase target)
   at ILGPU.Frontend.CodeGenerator.TryGenerateCode(Block block, IRBuilder builder, ILInstruction instruction)
   at ILGPU.Frontend.CodeGenerator.GenerateCode()
   at ILGPU.Frontend.CodeGenerationPhase.GenerateCodeInternal(MethodBase method, Boolean isExternalRequest, HashSet`1 detectedMethods, Method& generatedMethod)
   at ILGPU.Frontend.ILFrontend.DoWork()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The relevant code can be found [here](https://github.com/Czorio/WorldSculptor/blob/9b34c23e93d9c9250a51672efb972b1f07036036/SculptorCore/Filters/GPU/GpuBalaszErosionFilter.cs). I have made sure to link the code at the current commit so that future changes do not impact this question.

Through some trial and error with breakpoints I have figured out that the actual exception occurs at line 137, which is the compilation of the kernel.

I imagine that there is something I am doing wrong with my own datatypes, due to the `Invalid structure type` message, but I can't figure out what exactly that is.

**Comment by Czorio** [comment]
I had a brainflash and figured out that the vector classes in `System.Numeric` don't cause the issue. I originally was not even aware of the existence of these classes.

It would be nice to know which structs can be used in ILGPU kernels.

**Comment by m4rs-mt** [comment]
@Czorio Thank you for your bug report. I cloned your project and figured out what the problem is. ILGPU supports all blittable structure types (including your custom `VecX` types). However, your operations are declared to return abstract interfaces instead of actual structure types. Working on interfaces instead of structures involves boxing, which is not supported.

The error messages will be significantly improved in one of the next [releases](http://www.ilgpu.net/Home/Roadmap). This should simply debugging significantly 🔢
