### ISSUE TITLE
Memory error using blas with multiple accelerators

### ISSUE THREAD

**Issue by Ruberik** [m4rs-mt/ILGPU#623]
### The very short summary
The following series of function calls causes a crash:
```
accelerator0.Synchronize();
accelerator1.Synchronize();
blas0.Axpy(...)
blas1.Axpy(...)
accelerator0.Synchronize();
accelerator1.Synchronize();  // The crash happens here
```
I would have expected this set of function calls to execute the Axpy operations on each GPU without crashing. 

### The plot thickens
The following series of function calls _does not_ cause a crash:
```
accelerator0.Synchronize();
accelerator1.Synchronize();
blas0.Axpy(...)
accelerator1.Synchronize();  // This line was added. Note that nothing has happened on accelerator1 since the last Synchronize() call.
blas1.Axpy(...)
accelerator0.Synchronize();
accelerator1.Synchronize(); 
```

### The full repro
```
        static void Main(string[] args) {
            using (var context = Context.Create().Cuda().EnableAlgorithms().ToContext()) {
                var acceleratorCount = context.GetCudaDevices().Count;
                var accs = Enumerable.Range(0, acceleratorCount).Select(i => context.CreateCudaAccelerator(i)).ToArray();
                var blases = accs.Select(acc => new CuBlas(acc, CuBlasAPIVersion.V11)).ToArray();
                try {
                    Console.WriteLine($"Calling the one we expect to succeed");
                    AxPy0(accs, blases, true);
                    Console.WriteLine($"Calling the one we expect to crash");
                    AxPy0(accs, blases, false);
                } finally {
                    foreach (var b in blases) b.Dispose();
                    foreach (var acc in accs) acc.Dispose();
                }
            }
        }

        private static void AxPy0(CudaAccelerator[] accelerators, CuBlas[] blases, bool synchronizeBeforeCall) {
            int size = 1024;
            var derivs = accelerators.Select(x => x.Allocate1D<float>(size)).ToArray();
            var values = accelerators.Select(x => x.Allocate1D<float>(size)).ToArray();
            foreach (var acc in accelerators) acc.Synchronize();
            try {
                for (int i = 0; i < accelerators.Length; i++) {
                    Console.WriteLine($"  Sending calls to accelerator {i}");
                    var acc = accelerators[i];
                    var blas = blases[i];
                    if (synchronizeBeforeCall) acc.Synchronize();  // If false, crash. If true, no crash.
                    blas.Axpy(-0.01f, values[i].AsContiguous(), derivs[i].AsContiguous());
                }
                Console.WriteLine($"  Calls sent");
                for (int i = 0; i < accelerators.Length; i++) {
                    Console.WriteLine($"  Synchronizing accelerator {i}");
                    var acc = accelerators[i];
                    acc.Synchronize();
                    Console.WriteLine($"  accelerator {i} synchronized");
                }
            } finally {
                foreach (var x in derivs) x.Dispose();
                foreach (var x in values) x.Dispose();
            }
            Console.WriteLine($"  Success!");
        }
```
### The output
```
Calling the one we expect to succeed
  Sending calls to accelerator 0
  Sending calls to accelerator 1
  Calls sent
  Synchronizing accelerator 0
  accelerator 0 synchronized
  Synchronizing accelerator 1
  accelerator 1 synchronized
  Success!
Calling the one we expect to crash
  Sending calls to accelerator 0
  Sending calls to accelerator 1
  Calls sent
  Synchronizing accelerator 0
  accelerator 0 synchronized
  Synchronizing accelerator 1
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: an illegal memory access was encountered
   at ILGPU.Runtime.Cuda.CudaAccelerator.SynchronizeInternal()
   at ILGPU.Runtime.Accelerator.Synchronize()
   at Gotham.FurrowUtilities.Misc.AxPy0(CudaAccelerator[] accelerators, CuBlas[] blases, Boolean synchronizeBeforeCall) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 92
   at Gotham.FurrowUtilities.Misc.Main(String[] args) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 67
```
### The setup
* Windows 10 Pro, 64-bit
* ILGPU 1.0.0-rc1 (though this also happens on 0.10.1)
* ILGPU.Algorithms 1.0.0-rc1 (though this also happens on 0.10.0-beta1)
* Two Tesla P100 GPUs. Driver Version: 462.31. CUDA Version: 11.2.

**Comment by Ruberik** [comment]
Note that it also fails on a setup with four T4 GPUs, though weirdly it only crashes when we synchronize the last GPU.
```
Calling the one we expect to succeed
  Sending calls to accelerator 0
  Sending calls to accelerator 1
  Sending calls to accelerator 2
  Sending calls to accelerator 3
  Calls sent
  Synchronizing accelerator 0
  accelerator 0 synchronized
  Synchronizing accelerator 1
  accelerator 1 synchronized
  Synchronizing accelerator 2
  accelerator 2 synchronized
  Synchronizing accelerator 3
  accelerator 3 synchronized
  Success!
Calling the one we expect to crash
  Sending calls to accelerator 0
  Sending calls to accelerator 1
  Sending calls to accelerator 2
  Sending calls to accelerator 3
  Calls sent
  Synchronizing accelerator 0
  accelerator 0 synchronized
  Synchronizing accelerator 1
  accelerator 1 synchronized
  Synchronizing accelerator 2
  accelerator 2 synchronized
  Synchronizing accelerator 3
Unhandled exception. ILGPU.Runtime.Cuda.CudaException: an illegal memory access was encountered
   at ILGPU.Runtime.Cuda.CudaAccelerator.SynchronizeInternal()
   at ILGPU.Runtime.Accelerator.Synchronize()
   at Gotham.FurrowUtilities.Misc.AxPy0(CudaAccelerator[] accelerators, CuBlas[] blases, Boolean synchronizeBeforeCall) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 102
   at Gotham.FurrowUtilities.Misc.Main(String[] args) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 77
```

**Comment by Ruberik** [comment]
### A related problem
I can't call blas.Gemm without a crash, unless the accelerator on which blas.Gemm was called is _the last accelerator to have been synced_. That's demonstrated in this code:

```
        static void Main(string[] args) {
            using (var context = Context.Create().Cuda().EnableAlgorithms().ToContext()) {
                var accs = Enumerable.Range(0, context.GetCudaDevices().Count).Select(i => context.CreateCudaAccelerator(i)).ToArray();
                var blases = accs.Select(acc => new CuBlas(acc, CuBlasAPIVersion.V11)).ToArray();
                try {
                    Console.WriteLine($"Calling the one we expect to succeed");
                    Gmm0(accs, blases, true);
                    Console.WriteLine($"Calling the one we expect to crash");
                    Gmm0(accs, blases, false);
                } finally {
                    foreach (var b in blases) b.Dispose();
                    foreach (var acc in accs) acc.Dispose();
                }
            }
        }

        private static void Gmm0(CudaAccelerator[] accelerators, CuBlas[] blases, bool synchronizeBeforeCall) {
            var startTime = DateTime.Now;
            void LogTime(string s) { var timeSpent = DateTime.Now.Subtract(startTime).TotalSeconds; Console.WriteLine($"{DateTime.Now}\tTime to {s}: {timeSpent:0.0000}s"); startTime = DateTime.Now; }
            int size = 1 << 10;
            var As = accelerators.Select(x => x.Allocate1D<float>(size * size)).ToArray();
            var Bs = accelerators.Select(x => x.Allocate1D<float>(size * size)).ToArray();
            var Cs = accelerators.Select(x => x.Allocate1D<float>(size * size)).ToArray();

            try {
                var i = 0;
                accelerators[0].Synchronize();
                accelerators[1].Synchronize();
                if (synchronizeBeforeCall) accelerators[0].Synchronize();
                blases[i].Gemm(CuBlasOperation.NonTranspose, CuBlasOperation.NonTranspose, size, size, size, 1f, As[i].AsContiguous(), size, Bs[i].AsContiguous(), size, 1f, Cs[i].AsContiguous(), size);
            } finally {
                foreach (var x in As) x.Dispose();
                foreach (var x in Bs) x.Dispose();
                foreach (var x in Cs) x.Dispose();
            }
        }
```
Note that in the first call, we call acc0.Sync, acc1.Sync, acc0.Sync, and it works fine. In the second call, we call acc0.Sync, acc1.Sync and it crashes.

Output:
```
Calling the one we expect to succeed
Calling the one we expect to crash
Unhandled exception. ILGPU.Runtime.Cuda.CuBlasException: Exception of type 'ILGPU.Runtime.Cuda.CuBlasException' was thrown.
   at ILGPU.Runtime.Cuda.CuBlas`1.Gemm(CuBlasOperation transa, CuBlasOperation transb, Int32 m, Int32 n, Int32 k, Single alpha, ArrayView`1 a, Int32 lda, ArrayView`1 b, Int32 ldb, Single beta, ArrayView`1 c, Int32 ldc)
   at Gotham.FurrowUtilities.Misc.Gmm0(CudaAccelerator[] accelerators, CuBlas[] blases, Boolean synchronizeBeforeCall) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 87
   at Gotham.FurrowUtilities.Misc.Main(String[] args) in C:\Gotham\main\FurrowUtilities\Misc\Misc.cs:line 66
```
```

**Comment by MoFtZ** [comment]
hi @Ruberik. My guess is that you are running into an issue with CuBlas using the wrong device/accelerator. The CUDA documentation refers to [Device Selection](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-selection), where the programmer needs to manually switch between devices. The issue sounds like CuBlas is using a different device than it was created with.

Internally to ILGPU, methods like `accelerator.Synchronize()` perform this device selection by calling `accelerator.Bind()`. That is probably why calling `accelerator.Synchronize()` is "fixing" your problem.

As a workaround, you should manually call `accelerator.Bind()` to ensure that the correct device for the CuBlas instance is chosen.

**Comment by Ruberik** [comment]
Awesome! Thanks a lot for diagnosing and fixing this.
