### ISSUE TITLE
InternalCompilerException

### ISSUE THREAD

**Issue by RonaldIaxaduv** [m4rs-mt/ILGPU#641]
Hey there,
I'm currently writing code to convert pixels of an image to various colour spaces and I've already gotten the first few of them to work, but I've now come across an exception that I don't quite know how to tackle. I must admit that I'm rather inexperienced with GPU programming (I'm actually using ILGPU to learn more about it), so this might be a simple error on my end.

So here's the situation:
I'm running version 1.0.0-rc2 of both ILGPU and ILGPU.Algorithms and my GPU is an NVIDIA GeForce 840M with the latest drivers (which support Cuda). My project is using the .NET Framework 5.0.
In my main class, I'm creating a context and an accelerator instance that I'm passing to the class which handles the colour conversions:
```
//init context and accelerator
curContext = Context.CreateDefault();
curAccelerator = curContext.CreateCudaAccelerator(0);
```
The kernels that perform the conversions all follow the same principle, they basically look like this:
```
private static void Kernel_RGBToHSL(Index1D index, int width, int height, ArrayView<byte> argb, ArrayView<Point> parsing, ArrayView<float> h, ArrayView<float> s, ArrayView<float> l, ArrayView<float> alpha)
        {
            //get position
            Point parsingPos = parsing[index]; //point in image after parsing has been applied (used to change the order that the pixels are evaluated in e.g. row-wise, column-wise etc.)
            int argbIndex = (parsingPos.Y * width + parsingPos.X) * 4; //position of the pixel's ARGB values at the parsing position (*4 because the values are stored one after the other)

            //convert using the ColourHSL struct
            ColourHSL hsl = ColourHSL.FromRGB(argb[argbIndex + 3], argb[argbIndex + 2], argb[argbIndex + 1], argb[argbIndex + 0]); //converts ARGB (byte) to HSL (all values within [-1...1])

            //store
            h[index] = hsl.H;
            s[index] = hsl.S;
            l[index] = hsl.L;
            alpha[index] = hsl.Alpha;
        }

private static void Kernel_HSLToRGB(Index1D index, int width, int height, ArrayView<float> h, ArrayView<float> s, ArrayView<float> l, ArrayView<float> alpha, ArrayView<Point> parsing, ArrayView<byte> argb)
        {
            //get position
            Point parsingPos = parsing[index];
            int hslIndex = index.X; //position of the hsl values
            int argbIndex = (parsingPos.Y * width + parsingPos.X) * 4; //position of argb value in the output view according to the parsing

            //convert using the ColourHSL struct. The ColourRGBNonNull struct acts basically like System.Drawing.Color but cannot be null
            ColourRGBNonNull rgb = (new ColourHSL(h[hslIndex], s[hslIndex], l[hslIndex], alpha[hslIndex])).ToRGBNonNull();

            //store
            argb[argbIndex + 3] = rgb.Alpha;
            argb[argbIndex + 2] = rgb.R;
            argb[argbIndex + 1] = rgb.G;
            argb[argbIndex + 0] = rgb.B;
        }
```
So when I'm doing a different colour space, I only have to create a new struct that handles the calculations for that colour space. I've already done so for CMY/CMYK and those kernels worked fine, so I know that my current problem lies in the conversion operations themselves.
The conversion from RGB to HSL is working fine (it doesn't produce any out-of-range or NaN values or anything either), but when I'm converting from HSL to RGB I'm getting an InternalCompilerException when I'm creating the Action object to execute the kernel
```
var launchHSLToRGB = accelerator.LoadAutoGroupedStreamKernel<Index1D, int, int, ArrayView<float>, ArrayView<float>, ArrayView<float>, ArrayView<float>, ArrayView<Point>, ArrayView<byte>>(Kernel_HSLToRGB);
```
that reads
```
Message:
An internal compiler error has been detected

Stacktrace:
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile[TBackendHook](EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
   at ILGPU.Backends.Backend.Compile(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.CompileKernel(EntryPointDescription& entry, KernelSpecialization& specialization)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass157_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadAutoGroupedKernel[TDelegate](MethodInfo method)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedKernel[TIndex,T1,T2,T3,T4,T5,T6,T7,T8](Accelerator accelerator, Action`9 action)
   at ILGPU.Runtime.KernelLoaders.LoadAutoGroupedStreamKernel[TIndex,T1,T2,T3,T4,T5,T6,T7,T8](Accelerator accelerator, Action`9 action)
   at [...].ImageConverter.GetBitmap(List`1 samples, ParsingMethod pm, ColourConversionScheme ccs, Int32 width, Int32 height, Boolean includeAlpha) in [...]\ImageConverter.cs:line 1268
```
which didn't really tell me much to be honest (the line that's mentioned is where I'm creating the Action object). After some testing I've decided to check the inner exception though:
```
Inner exception:
System.AggregateException: One or more errors occurred. (The function 'Rem' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?)
 ---> ILGPU.Backends.NotSupportedIntrinsicException: The function 'Rem' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?
   at ILGPU.Backends.PTX.PTXInstructions.GetArithmeticOperation(BinaryArithmeticKind kind, ArithmeticBasicValueType type, CudaCapabilityContext capabilities, Boolean fastMath)
   at ILGPU.Backends.PTX.PTXCodeGenerator.GenerateCode(BinaryArithmeticValue value)
   at ILGPU.Backends.BackendCodeGenerator.BackendValueVisitor`1.Visit(BinaryArithmeticValue value)
   at ILGPU.IR.Values.BinaryArithmeticValue.Accept[T](T visitor)
   at ILGPU.Backends.BackendCodeGenerator.GenerateCodeFor[TCodeGenerator](TCodeGenerator codeGenerator, Value value)
   at ILGPU.Backends.PTX.PTXCodeGenerator.GenerateCodeInternal(Int32 registerOffset)
   at ILGPU.Backends.PTX.PTXKernelFunctionGenerator.GenerateCode()
   at ILGPU.Backends.CodeGeneratorBackend`4.<>c__DisplayClass1_0.<Compile>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at ILGPU.Backends.CodeGeneratorBackend`4.Compile(EntryPoint entryPoint, BackendContext& backendContext, KernelSpecialization& specialization)
   at ILGPU.Backends.Backend.Compile[TBackendHook](Method kernelMethod, EntryPointDescription& entry, KernelSpecialization& specialization, TBackendHook backendHook)
```
so the problem seems to be
```
The function 'Rem' does not have an intrinsic implementation for this backend. 'EnableAlgorithms' from the Algorithms library not invoked?
```
I'm assuming "Rem" refers to the modulo operator? This would kind of make sense since the HSL->RGB conversion is the first where I'm doing a modulo calculation:
```
private static float GetX(float C, float scaledH)
        {
            float abs = (scaledH % 2f) - 1;
            if (abs >= 0)
                return C * (1 - abs);
            else
                return C * (1 + abs);
        }
```
So, like the inner exception suggested, I tried calling EnableAlgorithms on my context before executing the kernel:
```
curContext = Context.CreateDefault();
curContext.EnableAlgorithms();
curAccelerator = curContext.CreateCudaAccelerator(0);
```
However, this is now throwing me a MethodAccessException:
```
Message:
Attempt by method 'ILGPU.AlgorithmContext.EnableAlgorithms(ILGPU.Context)' to access method 'ILGPU.Context.get_IntrinsicManager()' failed.

Stacktrace:
   at ILGPU.AlgorithmContext.EnableAlgorithms(Context context)
   at [...].MainWindow..ctor() in [...]\MainWindow.xaml.cs:line 160

Inner exception:

Target site:
Void EnableAlgorithms(ILGPU.Context)
```
and this is basically where I'm at my wits end, I don't know how to fix this.
I had a suspicion that maybe I need a custom Context for this instead of the default one, so I've tried creating one like in the [AlgorithmsMath Sample](https://github.com/m4rs-mt/ILGPU.Samples/blob/master/Src/AlgorithmsMath/Program.cs) (I believe this is the only sample that currently uses context.EnableAlgorithms?), but apparently it isn't possible to create a Context through a constructor like this anymore. I've attempted to create a context with the Context.Builder class, but the EnableAlgorithms method still gave me the same exception.
It's not possible to just use the XMath class either, since I would need to call context.EnableAlgorithms for that class as well (it seems to throw me the same exception as before when I replace `scaledH % 2f` with `XMath.Rem(scaledH, 2f)`).

Soooooo what exactly am I missing here? Again, apologies in advance in case this is a simple mistake on my end. Of course I can also share the rest of the conversion code if that helps.

**Comment by RonaldIaxaduv** [comment]
Thank you very much for the quick reply and for the fix! Works like a charm now! I didn't even notice that the samples have been moved, whoops. I'm really glad you mentioned it though, they've been a huge help!
