### ISSUE TITLE
Can't create Reduction - a PTX JIT compilation failed

### ISSUE THREAD

**Issue by mfagerlund** [m4rs-mt/ILGPU#673]
I have a lot of old code that I haven't used for a while, that uses ILGPU. I tried upgrading to the latest nuget packages for both ILGPU and ILGPU.Algorithms, and after the update, large parts of my code don't work anymore. It seems mostly related to Algorithms, like below where I can't even create a reduction.

       ```
        public void CantCreateReductionTest()
        {
            using (var context = new Context())
            {
                context.EnableAlgorithms();
                using (var accelerator = new CPUAccelerator(context))
                {
                    accelerator.CreateReduction<float, MinFloat>();
                    Console.WriteLine("Worked for CPU");
                }
                
                using (var accelerator = new CudaAccelerator(context))
                {
                    accelerator.CreateReduction<float, MinFloat>();
                    Console.WriteLine("Worked for Cuda");
                }
            }
        }
```

CPU works, the error below is thrown at accelerator.CreateReduction

ILGPU.Runtime.Cuda.CudaException: a PTX JIT compilation failed
   at ILGPU.Runtime.Cuda.CudaException.ThrowIfFailed(CudaError cudaStatus)
   at ILGPU.Runtime.Cuda.CudaKernel..ctor(CudaAccelerator accelerator, PTXCompiledKernel kernel, MethodInfo launcher)
   at ILGPU.Runtime.Cuda.CudaAccelerator.CreateKernel(PTXCompiledKernel compiledKernel, MethodInfo launcher)
   at ILGPU.Runtime.KernelAccelerator`2.LoadKernelInternal(CompiledKernel kernel)
   at ILGPU.Runtime.Accelerator.LoadKernel(CompiledKernel kernel)
   at ILGPU.Runtime.Accelerator.DefaultKernelLoader.LoadKernel(Accelerator accelerator, CompiledKernel compiledKernel, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernelDirect[TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.<>c__DisplayClass173_0`1.<LoadGenericKernel>b__0(TKernelLoader& loader, KernelInfo& info)
   at ILGPU.Runtime.Accelerator.LoadCachedKernel[TKernelLoader,T](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, CachedKernelLoader`2 cachedLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TKernelLoader](EntryPointDescription entry, KernelSpecialization specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadGenericKernel[TDelegate,TKernelLoader](EntryPointDescription& entry, KernelSpecialization& specialization, TKernelLoader& kernelLoader, KernelInfo& kernelInfo)
   at ILGPU.Runtime.Accelerator.LoadKernel[TDelegate](MethodInfo method, KernelSpecialization specialization, KernelInfo& kernelInfo)
   at ILGPU.Runtime.KernelLoaders.LoadKernel[T1,T2](Accelerator accelerator, Action`2 action, KernelInfo& kernelInfo)
   at ILGPU.Runtime.KernelLoaders.LoadKernel[T1,T2](Accelerator accelerator, Action`2 action)
   at ILGPU.Algorithms.ReductionExtensions.CreateReduction[T,TReduction](Accelerator accelerator)
   at Hagrid.Tests.WerkingTests.CantCreateReductionTest()

**Comment by mfagerlund** [comment]
I downloaded the ILGPU code and tried using the ILGPU.Samples solution to add a similar test, and there it works;

Is there a newer nuget package that I should be using instead? Seem to be some large-ish changes coming.

```
        static void Main()
        {
            using (var context =
                Context.Create(builder => builder.Cuda().EnableAlgorithms()))
            {
                foreach (var device in context.GetCudaDevices())
                {
                    using var accelerator = device.CreateCudaAccelerator(context);
                    accelerator.CreateReduction<float, Stride1D.Dense, MinFloat>();
                    Console.WriteLine("Worked this time!");
                }
            }
        }
```

**Comment by MoFtZ** [comment]
@mfagerlund When using ILGPU v0.9.x, you need to make sure to pair it with ILGPU.Algorithms v0.9.x.

There is also ILGPU v0.10.x, and ILGPU.Algorithms v0.10.0-beta1.

**Comment by Mattias-NCVIB** [comment]
Ok, makes sense. I found the v0.10.0 beta, but I couldn't figure out how to rewrite my code to make it work. Currently trying to see if I can migrate to RC-2.

/m
